base/urls.py
# -*- coding: utf-8 -*-
__author__ = 'sistemas'
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'base.views',
    url(r'^$', 'home__view', name='home'),
    url(r'^salir/$', 'logout_view', name='logout')
    # url(r'^blog/', include('blog.urls')),
)

beneficiaries/urls.py
# -*- coding: utf-8 -*-
__author__ = 'sistemas'
from django.conf.urls import patterns, url

from .views import CreateBeneficiaryView, ListBeneficiaryView, EditBeneficiaryView

urlpatterns = patterns(
    'beneficiaries.views',
    url(r'^$', ListBeneficiaryView.as_view(), name='home'),
    url(r'^add/$', CreateBeneficiaryView.as_view(), name='add'),
    url(r'^edit/(?P<pk>[\d]+)/$', EditBeneficiaryView.as_view(), name='edit'),
)

checkingrequest/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'chekingrequest.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^solicitudcheques/', include('base.urls', namespace='base')),
    url(r'^solicitudcheques/solicitudes/', include('reqcheck.urls', namespace='request')),
    url(r'^solicitudcheques/beneficiarios/', include('beneficiaries.urls', namespace='beneficiary')),


    url(r'^solicitudcheques/admin/', include(admin.site.urls)),
)

base/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models


class TimeStampUser(models.Model):
    create_at = models.DateTimeField(
        auto_now_add=True
    )
    update_at = models.DateTimeField(
        auto_now=True
    )
    by_user = models.ForeignKey(
        User,
        related_name='%(app_label)s_%(class)s_ownership'
    )

    class Meta:
        abstract = True

beneficiaries/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from base.models import TimeStampUser


@python_2_unicode_compatible
class TypeIdentification(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name='Tipo de identificación'
    )

    class Meta:
        verbose_name = 'Tipo de identificación'
        verbose_name_plural = 'Tipos de identificación'

    def __str__(self):
        return '%s' % self.name


@python_2_unicode_compatible
class Beneficiary(TimeStampUser):
    type = models.ForeignKey(
        TypeIdentification,
        verbose_name='Tipo'
    )
    id = models.BigIntegerField(
        primary_key=True,
        unique=True,
        verbose_name='Identificación'
    )
    dv = models.PositiveIntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(9)
        ],
        null=True,
        blank=True
    )
    name = models.CharField(
        max_length=100,
        verbose_name='Nombre'
    )

    class Meta:
        verbose_name = 'Beneficiario'
        verbose_name_plural = 'Beneficiarios'

    def __str__(self):
        return '%s' % self.name

beneficiaries/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
__author__ = 'sistemas'
from django import forms

from .models import Beneficiary


class BeneficiaryForm(forms.ModelForm):
    id = forms.IntegerField(
        widget=forms.TextInput,
        label='Identificación'
    )
    dv = forms.IntegerField(
        widget=forms.TextInput(
            attrs={'class': 'input--2d'}
        ),
        required=False
    )
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Nombre', 'class': 'input--full-width'}
        )
    )

    class Meta:
        model = Beneficiary
        fields = '__all__'

beneficiaries/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView

from base.mixins import LoginRequiredMixin

from .forms import BeneficiaryForm
from .models import Beneficiary


class ListBeneficiaryView(LoginRequiredMixin, ListView):
    model = Beneficiary
    template_name = 'beneficiaries--home.html'

    def get_queryset(self):
        queryset = self.model.objects.all().order_by('name')

        return queryset


class CreateBeneficiaryView(LoginRequiredMixin, CreateView):
    form_class = BeneficiaryForm
    template_name = 'beneficiaries--add-edit.html'
    success_url = reverse_lazy('beneficiary:home')


class EditBeneficiaryView(LoginRequiredMixin, UpdateView):
    model = Beneficiary
    form_class = BeneficiaryForm
    template_name = 'beneficiaries--add-edit.html'
    success_url = reverse_lazy('beneficiary:home')

beneficiaries/templates/beneficiaries--add-edit.html
{% extends 'base--loged.html' %}
{% block wrapper--loged %}
    <div class="header__modules">
        <h2 class="header__modules__tittle">Agregar Beneficiario</h2>
        <div class="header__actions">
            <a href="{% url 'beneficiary:home' %}" class="btn btn--default"><i class="fa fa-arrow-circle-left"></i> Ver Listado</a>
        </div>
    </div>
    <section class="form-modules form-modules__beneficiary">
        <form action="." method="post">
            {% csrf_token %}
            <input type="hidden" id="id_by_user" name="by_user" value="{{ user.id }}"/>
            <div class="form-modules--row form-modules--row-justify">
                {{ form.type.label_tag }} {{ form.type }} {{ form.type.errors }}
            </div>
            <div class="form-modules--row form-modules--row-left">
                {{ form.id.label_tag }} {{ form.id }} - {{ form.dv }} {{ form.id.errors }}
            </div>
            <div class="form-modules--row">
                {{ form.name }} {{ form.name.errors }}
            </div>
            <div class="form-modules--row form-modules--row-right">
                <button type="submit" class="btn btn--default"><i class="fa fa-save"></i> Guardar</button>
            </div>
        </form>
    </section>
{% endblock %}

beneficiaries/templates/beneficiaries--home.html
{% extends 'base--loged.html' %}
{% block wrapper--loged %}
    <div class="header__modules">
        <h2 class="header__modules__tittle">Beneficiarios</h2>
        <div class="header__actions">
            <a href="{% url 'beneficiary:add' %}" class="btn btn--default"><i class="fa fa-plus-circle"></i> Crear Beneficiario</a>
        </div>
    </div>
    <section class="list__items__module">
        <table>
            <thead>
                <tr>
                    <th>Identificación</th>
                    <th>Tipo</th>
                    <th>Nombre</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for e in object_list %}
                    <tr>
                        <td>{{ e.id }}{% if e.dv %} - {{ e.dv }}{% endif %}</td>
                        <td>{{ e.type.name }}</td>
                        <td>{{ e.name }}</td>
                        <td><a href="{% url 'beneficiary:edit' e.id %}" class="btn btn--warning"><i class="fa fa-edit"></i> Editar</a></td>
                    </tr>
                {% endfor%}
            </tbody>
        </table>

    </section>
{% endblock %}