base/urls.py
# -*- coding: utf-8 -*-
__author__ = 'sistemas'
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'base.views',
    url(r'^$', 'home__view', name='home'),
    url(r'^salir/$', 'logout_view', name='logout')
    # url(r'^blog/', include('blog.urls')),
)

checkingrequest/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'chekingrequest.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^solicitudcheques/', include('base.urls', namespace='base')),
    url(r'^solicitudcheques/solicitudes/', include('reqcheck.urls', namespace='request')),
    url(r'^solicitudcheques/beneficiarios/', include('beneficiaries.urls', namespace='beneficiary')),


    url(r'^solicitudcheques/admin/', include(admin.site.urls)),
)

reqcheck/urls.py
# -*- coding: utf-8 -*-
__author__ = 'sistemas'
from django.conf.urls import patterns, url

from .views import ListRequestView, EditRequestView, ListLegalizationView, DetailRequestView, CreateRequestView, \
    ListRequestApi

urlpatterns = patterns(
    'reqcheck.views',
    url(r'^$', ListRequestView.as_view(), name='home'),
    url(r'^search/$', 'search_view', name='search'),
    url(r'^api/list_request/$', ListRequestApi.as_view(), name='api_home'),
    url(r'^add/$', CreateRequestView.as_view(), name='add'),
    url(r'^edit/(?P<pk>[\d]+)/$', EditRequestView.as_view(), name='edit'),
    url(r'^detail/(?P<pk>[\d]+)/$', DetailRequestView.as_view(), name='detail'),
    url(r'^legalizaciones/$', ListLegalizationView.as_view(), name='legalization'),
    url(r'^legalizaciones/legalize/(?P<req>[\d]+)/$', 'legalize_request', name='legalize'),
    url(r'^turn/(?P<req>[\d]+)/$', 'turn_request', name='turn'),
    url(r'^cancel/(?P<req>[\d]+)/$', 'cancel_request', name='cancel'),
    url(r'^print/(?P<reqnumber>[\d]+)/$', 'print_request', name='print'),
    url(r'^approve/(?P<req>[\d]+)/$', 'approve_request', name='approve'),
    url(r'^add/beneficiary/?$', 'add_beneficiary', name='add_beneficiary'),
)

base/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models


class TimeStampUser(models.Model):
    create_at = models.DateTimeField(
        auto_now_add=True
    )
    update_at = models.DateTimeField(
        auto_now=True
    )
    by_user = models.ForeignKey(
        User,
        related_name='%(app_label)s_%(class)s_ownership'
    )

    class Meta:
        abstract = True

reqcheck/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import hashlib
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from base.models import TimeStampUser
from beneficiaries.models import Beneficiary
from employees.models import Petitioner


@python_2_unicode_compatible
class RequestType(TimeStampUser):
    type_request = models.CharField(
        max_length=50,
        verbose_name='Tipo de solicitud'
    )

    class Meta:
        verbose_name = 'Tipo de solicitud'
        verbose_name_plural = 'Tipos de solicitud'

    def __str__(self):
        return '%s' % self.type_request


@python_2_unicode_compatible
class Strategy(TimeStampUser):
    name = models.CharField(
        max_length=50,
        verbose_name='Estrategia'
    )

    class Meta:
        verbose_name = 'Estrategia'
        verbose_name_plural = 'Estrategias'

    def __str__(self):
        return '%s' % self.name


@python_2_unicode_compatible
class Project(TimeStampUser):
    name = models.CharField(
        max_length=100,
        verbose_name='Proyecto'
    )
    active = models.BooleanField(
        verbose_name='Activo',
        default=True
    )

    class Meta:
        verbose_name = 'Proyecto'
        verbose_name_plural = 'Proyectos'

    def __str__(self):
        return '%s' % self.name


class CategoryExpenditure(TimeStampUser):
    name = models.CharField(
        max_length=50,
        verbose_name='Rubro'
    )

    class Meta:
        verbose_name = 'Rubro'
        verbose_name_plural = 'Rubros'

    def __str__(self):
        return '%s' % self.name


@python_2_unicode_compatible
class RequestCheck(TimeStampUser):
    request_type = models.ForeignKey(
        RequestType,
        verbose_name='Tipo de Solicitud'
    )
    petitioner = models.ForeignKey(
        Petitioner,
        verbose_name='Empleado que solicita'
    )
    project = models.ForeignKey(
        Project,
        verbose_name='Proyecto'
    )
    category = models.ForeignKey(
        CategoryExpenditure,
        verbose_name='Rubro contable',
    )
    strategy = models.ForeignKey(
        Strategy,
        verbose_name='Estrategia'
    )
    date_event = models.DateField(
        verbose_name='Fecha del evento',
        default=datetime.datetime.now()
    )
    beneficiary = models.ForeignKey(
        Beneficiary,
        verbose_name='Beneficiario'
    )
    description = models.TextField(
        verbose_name='Descripción de la solicitud / Especificaciones técnicas',
        help_text='Maximo 255 caracteres'
    )
    observations = models.TextField(
        verbose_name='Justificación / Observaciones',
        null=True,
        blank=True
    )
    state = models.BooleanField(
        verbose_name='Estado',
        default=True
    )
    turned = models.BooleanField(
        verbose_name='Girado',
        default=False
    )
    value = models.BigIntegerField(
        verbose_name='Valor'
    )
    securecode = models.CharField(
        max_length=255,
        verbose_name='Codigo de seguridad',
        blank=True
    )
    date_legalitation = models.DateField(
        verbose_name='Fecha de legalización',
        blank=True,
        null=True,
    )
    printed = models.BooleanField(
        verbose_name='Impreso',
        default=False
    )
    approved = models.BooleanField(
        verbose_name='Aprobado',
        default=False
    )

    class Meta:
        verbose_name = 'Solicitud de cheque'
        verbose_name_plural = 'Solicitudes de cheques'
        permissions = (('can_auth_request', 'Autorizar solicitudes'), )

    def save(self, *args, **kwargs):
        securecode_string = hashlib.md5(
            (
                str(self.user) + '-' +
                str(self.petitioner) + '-' +
                str(self.date_create) + '-' +
                str(self.value)
            ).encode('utf-8')
        ).hexdigest()
        self.securecode = securecode_string
        super(RequestCheck, self).save(*args, **kwargs)

    def __str__(self):
        return 'Solicitud No - %s' % self.id

    def user(self):
        return '%s' % self.by_user

    def date_create(self):
        return '%s' % self.create_at

reqcheck/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.template.loader import render_to_string

from employees.models import AssigningEmployee
from .models import RequestCheck, Project, CategoryExpenditure
from beneficiaries.models import Beneficiary


class SelectWithPop(forms.Select):

    def render(self, name, *args, **kwargs):
        html = super(SelectWithPop, self).render(name, *args, **kwargs)
        popupplus = render_to_string("popupplus.html", {'field': name})

        return html + popupplus


class MultipleSelectWithPop(forms.Select):

    def render(self, name, *args, **kwargs):
        html = super(MultipleSelectWithPop, self).render(name, *args, **kwargs)
        popupplus = render_to_string("popupplus.html", {'field': name})

        return html + popupplus


class RequestForm(forms.ModelForm):
    beneficiary = forms.ModelChoiceField(
        Beneficiary.objects,
        widget=SelectWithPop,
        label='Beneficiario'
    )

    class Meta:
        model = RequestCheck
        exclude = ['securecode', 'date_legalitation', 'turned', 'printed', 'approved']

    def __init__(self, user, *args, **kwargs):
        # print user
        super(RequestForm, self).__init__(*args, **kwargs)
        # Filtro por usuario para traer solo los Solicitantes asignados al usuario
        projects = Project.objects.filter(active=True)
        if not user.is_superuser:
            assign = AssigningEmployee.objects.get(user_assignment=user).petitioner.all()
            self.fields['petitioner'].queryset = assign
        self.fields['project'].queryset = projects
        if user.id not in [1, 11, 12]:
            categories_filter = CategoryExpenditure.objects.all()[1:4]
        else:
            categories_filter = CategoryExpenditure.objects.all()
        categories = CategoryExpenditure.objects.filter(id__in=categories_filter)
        self.fields['category'].queryset = categories


class SearchForm(forms.Form):
    beneficiary = forms.CharField(
        required=False,
        label='Beneficiario '
    )
    from_date = forms.DateField(
        required=False,
        label='Desde '
    )
    to_date = forms.DateField(
        required=False,
        label='Hasta '
    )

reqcheck/templates/legalization--home.html
{% extends 'base--loged.html' %}
{% load humanize %}
{% load static from staticfiles %}
{% block wrapper--loged %}
    <div class="header__modules">
        <h2 class="header__modules__tittle">Solicitudes pendientes de legalizar</h2>
        <div class="header__actions">
            <a href="{% url 'request:add' %}" class="btn btn--default"><i class="fa fa-plus-circle"></i> Crear Solicitud</a>
        </div>
    </div>
    <section class="list__items__module">
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Solicitante</th>
                    <th>Valor</th>
                    <th>Fecha Solicitud</th>
                    {% if user.is_staff %}
                        <th></th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for e in object_list %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.petitioner.name }}</td>
                        <td>{{ e.value|intcomma }}</td>
                        <td>{{ e.create_at|date:"d/m/Y" }}</td>
                        {% if user.is_staff %}
                            <td><a href="" class="btn btn--warning legalize" data-id="{{ e.id }}"><i class="fa fa-edit"></i> Legalizar</a></td>
                        {% endif %}
                    </tr>
                {% endfor%}
            </tbody>
        </table>

        <div class="pagination">
            <div class="step-links step-links--previus">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-arrow-circle-left"></i> Anterior</a>
                {% else %}
                    &nbsp;
                {% endif %}
            </div>
            <div class="current-page">
                Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
            </div>
            <div class="step-links step-links--next">
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Siguiente <i class="fa fa-arrow-circle-right"></i></a>
                {% else %}
                    &nbsp;
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static 'js/vendor/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

reqcheck/templates/popadd.html
{% load static from staticfiles %}
<!doctype html>
<html lang="es-co">
<head>
    <meta charset="UTF-8">
    <title>Agregar {{ field }}</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <script src="{% static 'js/RelatedObjectLookups.js' %}"></script>
</head>
<body>
    <div class="row">
        <div class="small-12 columns text-center">
            <h1>Agregar Beneficiario</h1>
        </div>
    </div>

    <section class="form-modules form-modules__beneficiary">
        <form action="/solicitudcheques/solicitudes/add/{{ field }}" method="post">
            {% csrf_token %}
            <input type="hidden" id="id_by_user" name="by_user" value="{{ user.id }}"/>
            <div class="form-modules--row form-modules--row-justify">
                {{ form.type.label_tag }} {{ form.type }} {{ form.type.errors }}
            </div>
            <div class="form-modules--row form-modules--row-left">
                {{ form.id.label_tag }} {{ form.id }} - {{ form.dv }} {{ form.id.errors }}
            </div>
            <div class="form-modules--row">
                {{ form.name }} {{ form.name.errors }}
            </div>
            <div class="form-modules--row form-modules--row-right">
                <button type="submit" class="btn btn--default"><i class="fa fa-save"></i> Guardar</button>
            </div>
        </form>
    </section>
</body>
</html>

reqcheck/templates/request--add.html
{% extends 'base--loged.html' %}
{% load static from staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/default.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/default.date.css' %}"/>
{% endblock %}
{% block jsTop %}
    <script src="{% static 'js/RelatedObjectLookups.js' %}"></script>
{% endblock %}
{% block wrapper--loged %}
    <div class="header__modules">
        <h2 class="header__modules__tittle">Crear Solicitud</h2>
        <div class="header__actions">
            <a href="{% url 'request:home' %}" class="btn btn--default"><i class="fa fa-arrow-circle-left"></i> Ver Listado</a>
        </div>
    </div>
    <section class="form-modules form-modules__request">
        <form action="." method="post">
            {{ form.media }}
            {% csrf_token %}
            <input type="hidden" id="id_by_user" name="by_user" value="{{ user.id }}"/>
            <div class="form-modules--row form-modules--row-justify">
                <div class="quarter-width">{{ form.request_type.label_tag }}{{ form.request_type }}{{ form.request_type.errors }}</div>
                <div class="quarter-width">{{ form.strategy.label_tag }}{{ form.strategy }}{{ form.strategy.errors }}</div>
                <div class="quarter-width">{{ form.project.label_tag }}{{ form.project }}{{ form.project.errors }}</div>
                <div class="quarter-width"><label for="id_category">Rubro contable:</label>{{ form.category }}{{ form.category.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.petitioner.label_tag }}{{ form.petitioner }}{{ form.petitioner.errors }}</div>
                <div class="half-width">{{ form.beneficiary.label_tag }}{{ form.beneficiary }}{{ form.beneficiary.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.description.label_tag }}</div>
                <div class="half-width">{{ form.description.help_text }}</div>
            </div>
            <div class="form-modules--row">
                <div class="full-width">{{ form.description }}{{ form.description.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="full-width">{{ form.observations.label_tag }}{{ form.observations }}{{ form.observations.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.date_event.label_tag }}{{ form.date_event }}{{ form.date_event.errors }}</div>
                <div class="half-width">{{ form.value.label_tag }}{{ form.value }}{{ form.value.errors }}</div>
            </div>
            {{ form.state.as_hidden }}

            <div class="form-modules--row form-modules--row-right">
                <button type="submit" class="btn btn--default"><i class="fa fa-save"></i> Guardar</button>
            </div>
        </form>
    </section>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static 'js/vendor/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/vendor/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'js/vendor/picker.js' %}"></script>
    <script src="{% static 'js/vendor/picker.date.js' %}"></script>
    <script src="{% static 'js/vendor/translations/es_ES.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('#id_beneficiary').chosen();
            $('#id_date_event').pickadate(
                    {
                        format: 'dd/mm/yyyy'
                    }
            )
        });
    </script>
{% endblock %}

reqcheck/templates/request--edit.html
{% extends 'base--loged.html' %}
{% load static from staticfiles %}
{% block wrapper--loged %}
    <div class="header__modules">
        <h2 class="header__modules__tittle">Crear Solicitud</h2>
        <div class="header__actions">
            <a href="{% url 'request:home' %}" class="btn btn--default"><i class="fa fa-arrow-circle-left"></i> Ver Listado</a>
        </div>
    </div>
    <section class="form-modules form-modules__request">
        <form action="." method="post">
            {{ form.media }}
            {% csrf_token %}
            <input type="hidden" id="id_by_user" name="by_user" value="{{ user.id }}"/>
            <div class="form-modules--row form-modules--row-justify">
                <div class="quarter-width">{{ form.request_type.label_tag }}{{ form.request_type }}{{ form.request_type.errors }}</div>
                <div class="quarter-width">{{ form.strategy.label_tag }}{{ form.strategy }}{{ form.strategy.errors }}</div>
                <div class="quarter-width">{{ form.project.label_tag }}{{ form.project }}{{ form.project.errors }}</div>
                <div class="quarter-width"><label for="id_category">Rubro contable:</label>{{ form.category }}{{ form.category.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.petitioner.label_tag }}{{ form.petitioner }}{{ form.petitioner.errors }}</div>
                <div class="half-width">{{ form.beneficiary.label_tag }}{{ form.beneficiary }}{{ form.beneficiary.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.description.label_tag }}</div>
                <div class="half-width">{{ form.description.help_text }}</div>
            </div>
            <div class="form-modules--row">
                <div class="full-width">{{ form.description }}{{ form.description.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="full-width">{{ form.observations.label_tag }}{{ form.observations }}{{ form.observations.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.date_event.label_tag }}{{ form.date_event }}{{ form.date_event.errors }}</div>
                <div class="half-width">{{ form.value.label_tag }}{{ form.value }}{{ form.errors }}</div>
            </div>
            {{ form.state.as_hidden }}

            <div class="form-modules--row form-modules--row-right">
                <button type="submit" class="btn btn--default"><i class="fa fa-save"></i> Guardar</button>
            </div>
        </form>
    </section>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static 'js/vendor/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/vendor/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('#id_beneficiary').chosen();
        });
    </script>
{% endblock %}

reqcheck/templates/request--home.html
{% extends 'base--loged.html' %}
{% load static from staticfiles %}
{% load humanize %}
{% block wrapper--loged %}
    <div class="header__modules">
        <h2 class="header__modules__tittle">Solicitudes</h2>
        <div class="header__actions">
            <a href="{% url 'request:search' %}" class="btn btn--default"><i class="fa fa-search"></i> Buscar</a>
            <a href="{% url 'request:add' %}" class="btn btn--default"><i class="fa fa-plus-circle"></i> Crear Solicitud</a>
        </div>
    </div>
    <section class="list__items__module">
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Solicitante</th>
                    <th>Beneficiario</th>
                    <th>Valor</th>
                    <th>Fecha Solicitud</th>
                    <th>Proyecto</th>
                    <th>Rubro</th>
                    <th>Estado</th>
                    <th>Girado</th>
                    <th></th>
                    {% if user.is_staff %}
                        <th></th>
                    {% endif %}
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for e in object_list %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.petitioner.name }}</td>
                        <td>{{ e.beneficiary.name }}</td>
                        <td>{{ e.value|intcomma }}</td>
                        <td>{{ e.create_at|date:"d/m/Y" }}</td>
                        <td>{{ e.project.name }}</td>
                        <td>{{ e.category.name }}</td>
                        <td>{% if e.state %}<i class="fa fa-check-square-o success"></i>{% else %}<i class="fa fa-square-o failure"></i>{% endif %}</td>
                        <td>
                            {% if e.turned %}
                                <i class="fa fa-check-square-o success"></i>
                            {% else %}
                                {% if user.is_staff %}
                                    <a href="#" class="turn" data-id="{{ e.id }}"><i class="fa fa-square-o failure"></i></a>
                                {% else %}
                                    <i class="fa fa-square-o failure"></i>
                                {% endif %}
                            {% endif %}
                        </td>
                        <td><a href="{% url 'request:detail' e.id %}" class="btn btn--default"><i class="fa fa-eye"></i></a></td>
                        {% if user.is_staff %}
                            <td>
                                {% if e.state and e.approved %}
                                    <a href="{% url 'request:print' e.id %}" class="btn btn--default" title="Imprimir"><i class="fa fa-print"></i></a>
                                {% elif e.state and not e.approved and perms.reqcheck.can_auth_request %}
                                    <a href="#" class="btn btn--success approve" title="Aprobar" data-id="{{ e.id }}"><i class="fa fa-thumbs-up"></i></a>
                                {% endif %}
                            </td>
                        {% endif %}
                        <td>
                            {% if not e.approved and not e.turned and e.state or user.is_staff %}
                                <a href="{% url 'request:edit' e.id %}" class="btn btn--warning" title="Editar"><i class="fa fa-edit"></i></a>

                            {% endif %}
                        </td>
                        <td>
                            {% if not e.approved and not e.turned and e.state or user.is_staff and e.state %}
                                <a href="#" class="btn btn--warning cancel" title="Cancelar" data-id="{{ e.id }}"><i class="fa fa-times-circle"></i></a>
                            {% endif %}
                        </td>

                    </tr>
                {% endfor%}
            </tbody>
        </table>

        <div class="pagination">
            <div class="step-links step-links--previus">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-arrow-circle-left"></i> Anterior</a>
                {% else %}
                    &nbsp;
                {% endif %}
            </div>
            <div class="current-page">
                Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
            </div>
            <div class="step-links step-links--next">
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Siguiente <i class="fa fa-arrow-circle-right"></i></a>
                {% else %}
                    &nbsp;
                {% endif %}
            </div>
        </div>

    </section>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static 'js/vendor/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

reqcheck/templates/request--search.html
{% extends 'base--loged.html' %}
{% load static from staticfiles %}
{% load humanize %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/default.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/default.date.css' %}"/>
{% endblock %}
{% block wrapper--loged %}
    <div class="header__modules">
        <h2 class="header__modules__tittle">Solicitudes</h2>
        <div class="header__actions">
            <a href="{% url 'request:home' %}" class="btn btn--default"><i class="fa fa-arrow-circle-left"></i> Ver Listado</a>
            <a href="{% url 'request:add' %}" class="btn btn--default"><i class="fa fa-plus-circle"></i> Crear Solicitud</a>
        </div>
    </div>
    <div class="header__modules header__modules__search">
        <form id="form_search" action="." method="post">
            {% csrf_token %}
{#            Desde: {{ queryset.form.date_event__gte }}#}
{#            Hasta:{{ queryset.form.date_event__lte }}#}
            {{ form }}
            <button class="btn btn--default" type="submit"><i class="fa fa-search"></i> Buscar</button>
            <button class="btn btn--default" type="button" id="reset_form"><i class="fa fa-close"></i> Borrar</button>
        </form>
    </div>
    <section class="list__items__module">
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Solicitante</th>
                    <th>Beneficiario</th>
                    <th>Valor</th>
                    <th>Fecha Solicitud</th>
                    <th>Proyecto</th>
                    <th>Rubro</th>
                    <th>Estado</th>
                    <th>Girado</th>
                    <th></th>
                    {% if user.is_staff %}
                        <th></th>
                    {% endif %}
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for e in queryset %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.petitioner.name }}</td>
                        <td>{{ e.beneficiary.name }}</td>
                        <td>{{ e.value|intcomma }}</td>
                        <td>{{ e.create_at|date:"d/m/Y" }}</td>
                        <td>{{ e.project.name }}</td>
                        <td>{{ e.category.name }}</td>
                        <td>{% if e.state %}<i class="fa fa-check-square-o success"></i>{% else %}<i class="fa fa-square-o failure"></i>{% endif %}</td>
                        <td>
                            {% if e.turned %}
                                <i class="fa fa-check-square-o success"></i>
                            {% else %}
                                {% if user.is_staff %}
                                    <a href="#" class="turn" data-id="{{ e.id }}"><i class="fa fa-square-o failure"></i></a>
                                {% else %}
                                    <i class="fa fa-square-o failure"></i>
                                {% endif %}
                            {% endif %}
                        </td>
                        <td><a href="{% url 'request:detail' e.id %}" class="btn btn--default"><i class="fa fa-eye"></i></a></td>
                        {% if user.is_staff %}
                            <td>
                                {% if e.state %}
                                    <a href="{% url 'request:print' e.id %}" class="btn btn--default" title="Imprimir"><i class="fa fa-print"></i></a>
                                {% endif %}
                            </td>
                        {% endif %}
                        <td>
                            {% if not e.printed and not e.turned and e.state %}
                                <a href="{% url 'request:edit' e.id %}" class="btn btn--warning" title="Editar"><i class="fa fa-edit"></i></a>

                            {% endif %}
                        </td>
                        <td>
                            {% if not e.printed and not e.turned and e.state %}
                                <a href="#" class="btn btn--warning cancel" title="Cancelar" data-id="{{ e.id }}"><i class="fa fa-times-circle"></i></a>
                            {% endif %}
                        </td>

                    </tr>
                {% endfor%}
            </tbody>
        </table>

    </section>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static 'js/vendor/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/vendor/picker.js' %}"></script>
    <script src="{% static 'js/vendor/picker.date.js' %}"></script>
    <script src="{% static 'js/vendor/translations/es_ES.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('#id_from_date, #id_to_date').pickadate(
                    {
                        format: 'dd/mm/yyyy'
                    }
            );
        });
    </script>
{% endblock %}