base/urls.py
# -*- coding: utf-8 -*-
__author__ = 'sistemas'
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'base.views',
    url(r'^$', 'home__view', name='home'),
    url(r'^salir/$', 'logout_view', name='logout')
    # url(r'^blog/', include('blog.urls')),
)

checkingrequest/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'chekingrequest.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^solicitudcheques/', include('base.urls', namespace='base')),
    url(r'^solicitudcheques/solicitudes/', include('reqcheck.urls', namespace='request')),
    url(r'^solicitudcheques/beneficiarios/', include('beneficiaries.urls', namespace='beneficiary')),


    url(r'^solicitudcheques/admin/', include(admin.site.urls)),
)

base/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models


class TimeStampUser(models.Model):
    create_at = models.DateTimeField(
        auto_now_add=True
    )
    update_at = models.DateTimeField(
        auto_now=True
    )
    by_user = models.ForeignKey(
        User,
        related_name='%(app_label)s_%(class)s_ownership'
    )

    class Meta:
        abstract = True

base/forms.py
# -*- coding: utf-8 -*-
__author__ = 'sistemas'

from django.contrib.auth.forms import AuthenticationForm
from django import forms


class MyAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Usuario', 'class': 'form-login__input--user'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Contraseña', 'class': 'form-login__input--pass'}
        )
    )

base/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect

from .forms import MyAuthenticationForm


def home__view(request):
    if request.user.is_authenticated():
        return render(request, 'base--home.html')
    else:
        form = MyAuthenticationForm(request, request.POST or None)
        if form.is_valid():
            if form.get_user() is not None:
                login(request, form.get_user())
                return redirect(request.path)
        ctx = {
            'form': form
        }
        return render(request, 'base--login.html', ctx)


def logout_view(request):
    logout(request)
    return redirect('/solicitudcheques/')

templates/base--loged.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block main %}
    <header class="header">
        <div class="header__wrapper">
            <h1 class="header__tittle">Solicitud de Cheques</h1>
            {% block header--loged %}{% endblock %}
            <div class="header__actions">
                <a href="{% url 'base:logout' %}" class="header__actions__buttons">
                    <i class="fa fa-sign-out"></i>
                </a>
                <p class="header__user"><i class="fa fa-user"></i> {{ user.get_full_name }}</p>
            </div>
        </div>
    </header>
    <div class="wrapper--loged">
        <section class="sidebar">
            <nav>
                <ul class="nav--list">
                    {% for i in menu %}
                        <li class="nav--item"><a href="{{ i.url }}" {% if i.active %}class="active" {% endif %}><i class="fa fa-{{ i.icon }}"></i>{{ i.name }}</a></li>
                    {% endfor %}
                    {% if user.is_superuser %}
                        <h3>Administración</h3>
                        {% for i in menu_admin %}
                            <li class="nav--item"><a href="{{ i.url }}" {% if i.active %}class="active" {% endif %}><i class="fa fa-{{ i.icon }}"></i>{{ i.name }}</a></li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </nav>
        </section>
        <section class="main">
            {% block wrapper--loged %}te{% endblock %}
        </section>
    </div>
    <footer class="footer">
        <p>Corporación Viva la Ciudadanía</p>
        {% block footer-loged %}{% endblock %}
    </footer>
{% endblock %}
{% block js %}

{% endblock %}

templates/base.html
{% load static from staticfiles %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Solicitud de cheques</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    {% block css %}{% endblock %}
    {% block jsTop %}{% endblock %}
</head>
<body>
    {% block main %}{% endblock %}
    {% block js %}{% endblock %}
</body>
</html>